blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask A Question
    url: https://github.com/jeet-khondker/nexus-pend-boilerplate/discussions/new?category=q-a
    about: Ask Questions & Discuss with the Community
  - name: ðŸ’¡ Feature Request Discussion
    url: https://github.com/jeet-khondker/nexus-pend-boilerplate/discussions/new?category=ideas
    about: Suggest An Idea for this Project (Discuss before Creating Issue)
  - name: ðŸ“š Documentation
    url: https://github.com/jeet-khondker/nexus-pend-boilerplate/tree/main/documentation
    about: View Comprehensive Project Documentation
  - name: ðŸ”’ Security Vulnerability
    url: https://github.com/jeet-khondker/nexus-pend-boilerplate/security/advisories/new
    about: Report a Security Vulnerability (DO NOT Create a ublic Issue)
  - name: ðŸ“– Contributing Guide
    url: https://github.com/jeet-khondker/nexus-pend-boilerplate/blob/main/CONTRIBUTING.md
    about: Learn How to Contribute to this Project
